language: swift
osx_image: xcode12
before_install:
  - gem install cocoapods xcpretty
  - pod repo update
script:
- pod lib lint --fail-fast --verbose --allow-warnings
notifications:
  email:
    recipients:
      - sergey.chausov@kaltura.com
    on_success: change
    on_failure: always
