# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SmartSwitchSample_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'PlayKitSmartSwitch', :path => '../../../'
  
  # pod 'KalturaPlayer/OTT', '~> 4.0'
  pod 'KalturaPlayer/OTT', :path => '../../../../kaltura-player-ios'
  
  # pod 'PlayKit', '~> 3.20'
  pod 'PlayKit', :path => '../../../../playkit-ios'
  
  pod 'KalturaNetKit', :path => '../../../../netkit-ios'
  pod 'PlayKitYoubora', :path => '../../../../playkit-ios-youbora'
  
end
